language: rust
cache: cargo
matrix:
  include:
  - os: linux
  - os: osx
  - rust: 1.30.0
  - rust: 1.30.0
    env: DIST_SCCACHE=1
  - rust: beta
  - rust: nightly
  - env: DEPLOY=1 TARGET=x86_64-apple-darwin
    script: cargo build --release --target $TARGET --features=all
    os: osx
  - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl
    before_script: "./scripts/travis-musl-openssl.sh"
    script: cargo build --release --target $TARGET --features=all
    addons:
      apt:
        packages:
        - musl-tools
  allow_failures:
  - rust: nightly
before_script:
- export EXTRA_FEATURES=
- if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export EXTRA_FEATURES="$EXTRA_FEATURES
  unstable"; fi
- if [[ "${DIST_SCCACHE}" = "1" ]]; then export EXTRA_FEATURES="$EXTRA_FEATURES dist-client
  dist-server"; fi
script:
- cargo build --verbose --features="all ${EXTRA_FEATURES}"
- RUST_BACKTRACE=1 cargo test --all --verbose --no-default-features --features="${EXTRA_FEATURES}"
- RUST_BACKTRACE=1 cargo test --all --verbose --features="all ${EXTRA_FEATURES}"
before_deploy:
- "./scripts/prep_deploy.sh"

deploy:
  api_key:
    secure: PihbJggVxG7UbwrArb4DwDzWuy1+JUC4JbnFBRScKo4gjFgBn6y46Gjm58xk6aiSjveA6xKuecE6/kkGwlVD+bCkRZerjdYaG8QPzylD1OwlGilWafC+0KStPtczdLwlD7weYpMl4ArMaO4i5mSaAZYbqo2UBuzjbGp0jQ0UD32Z4e3YcltGVZ1jhfQRn0PNoQ3yylIom+WNZavBxsSsnjNvGOrMpydYOZwX92Mo7UaQyIvjVkVvh1AA7Bbimt1xaXJ2strdTRs8DhHt7doHvrFEZkK7nW8wOAy8oUfZIJQy9hzs8m2noF2SatCj8uc5qfFORAMAe8JmdrAT/aTmkX8lMRpjgsJBdayy+gjyMsyHJHpo6xdY6HNBwYPwEczLxmcSarK8Kwv8hdSIdI/9NeUr+/H4TDSnhXj9VAEUV+yHmWWG3+0BrbxVSGmr1LlJ834lSkLuyVFllSP7IxyxXfoCYZue2K4XJER6OL4UASI1VQHj5Vm9H+LFD39iq2cgT+IqcbxFEVIi+AvLYWWaIRYKGuQ64dLbJOHBAwHHgH/QhshA4T6KDSqvHjjiWlNw0t7ZZiGVnEdk8N3uQP72P3NnWcIAdU343YqDQZlIZB0lAO4fck4kzKWiryjiThirWDMV29GiBnl4zNQ5yfJnn2//K65u3b9img2+MttvnOE=
  file:
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz.sha256
  on:
    condition: $DEPLOY = 1
    tags: true
    repo: Jake-Shadle/sccache
  provider: releases
  skip_cleanup: true
